FROM ubuntu:18.04

RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    wget \
    ca-certificates \
    libgmp3-dev \
    libprocps-dev \
    libboost-all-dev \
    libssl-dev \
    pkg-config \
    sudo \
    && rm -rf /var/lib/apt/lists/*

ENV GOROOT=/usr/local/go \
    GOPATH=/root/go \
    PATH=/usr/local/go/bin:/root/go/bin:$PATH \
    LD_LIBRARY_PATH=/usr/local/lib

RUN wget -q --no-check-certificate https://dl.google.com/go/go1.10.8.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.10.8.linux-amd64.tar.gz && \
    rm go1.10.8.linux-amd64.tar.gz && \
    mkdir -p $GOPATH/src/github.com

RUN cd $GOPATH/src/github.com && \
    git clone https://github.com/percyc/PFAP.git

WORKDIR /root/go/src/github.com/PFAP
RUN chmod +x build.sh && ./build.sh all

EXPOSE 2007 2008 8545 30303

CMD ["/bin/bash"]
